name: Generate ASCII Artwork


on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: List Repo files in the path
          run: ls -ltra
        

        - name: Executing Shell Script commands
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh


